sudo: required
services:
  - docker

before_install:
  - docker build -t marinaromanova/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true marinaromanova/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-3"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-eu-west-3-204722250708"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"