sudo: required
services:
  - docker

before_install:
  - docker build -t marinaromanova/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true marinaromanova/docker-react npm run test -- --coverage